### ISSUE TITLE
org-jira-get-issues-by-board -> jiralib agile retrieve: caught error: (wrong-type-argument listp [])

### ISSUE THREAD

**Issue by iqrow** [ahungry/org-jira#101]
When running `org-jira-get-issues-by-board`

It fetches all the issues for a board, but it appends only one issue and doesn't automatically navigate to the buffer.

```
REQUEST [debug] symbol-status = success
REQUEST [debug] Executing complete callback.
jiralib agile retrieve: got 740 values of 740
jiralib agile retrieve: calling callback
Tag :PROJ_1072: set in 1 headings
jiralib agile retrieve: caught error: (wrong-type-argument listp [])
```

Anything I can do to debug this? Thanks.

**Comment by ahungry** [comment]
@dudinea I believe you added this feature a couple months ago - any advice?

**Comment by duevgen** [comment]
The error happens inside the  org-jira-get-issues, which is called by the
org-jira-get-issue-list-callback with list of retrieved issues (and here is a lot of them: 740!).

So I believe that  the problem is not specific to the feature, but it's some generic issue with reading/formatting of JIRA issues because "agile" API  returns the issues in the same format as regular API.  And obviously It is hard to tell what is causing the error without seeing stacktrace and/or retrieved data.

As for debugging, I would  start from running org-jira-get-issues-by-board with debug-on-error set to t or with org-jira-get-issues instrumented using edebug.

Another option is to somehow collect the data that was returned from Jira and attach it here or send privately to one of the developers.

**Comment by dudinea** [comment]
The error happens inside the org-jira-get-issues, which is called by the
org-jira-get-issue-list-callback with list of retrieved issues (and here is a lot of them: 740!).

So I believe that the problem is not specific to the feature, but it's some generic issue with reading/formatting of JIRA issues because "agile" API returns the issues in the same format as regular API. And obviously It is hard to tell what is causing the error without seeing stacktrace and/or retrieved data.

As for debugging, I would start from running org-jira-get-issues-by-board with debug-on-error set to t or with org-jira-get-issues instrumented using edebug.

Another option is to somehow collect the data that was returned from Jira and attach it here or send privately to one of the developers.

**Comment by ahungry** [comment]
I tried this on a board with ~695 issues, ran into a different error:

`jiralib agile retrieve: caught error: (file-error Creating pipe Too many open files)`

(Emacs is likely opening an instance of the file/buffer per request)

I wonder if it would be better to change this to fetch the most recent N issues from a board, where N can be a user customized value.  Then, we can limit the default to the 50 latest created tickets, as some boards can be *much* larger than ~700 issues, and a fetch of 10,000 issues would almost always fail (and be useless for 99% of the users of this feature).

**Comment by dudinea** [comment]
Ok, I'll try to look into the issue with open file descriptors. 
As for limiting number of retrieved issues, I think it looks like a good idea on it's own, I'm looking forward implementing  limit as well as configurable filter using JQL query.

**Comment by winmillwill** [comment]
FWIW, I ran into this issue and toggling debug-on-error didn't do anything. Conveniently, I had pending package updates which triggered an error that did trip the debugger. Seems this error gets caught and printed such that debug-on-error doesn't get tripped.

**Comment by ahungry** [comment]
I think this may be irrelevant now with the `org-jira-get-issues-from-custom-jql` feature/command.
