### ISSUE TITLE
Remove unnecessary usage of `cl-function`

### ISSUE THREAD

**Issue by Fuco1** [ahungry/org-jira#115]
There's quite a lot of functions which use the `cl-function` wrapper for no good reason.  The following callback doesn't even use the `data` argument.  It could be just a simple lambda.  It makes things appear complicated for no additional benefit I think.

This

```elisp
(cl-function
 (lambda (&rest data &allow-other-keys)
   (org-jira-update-worklogs-for-current-issue)))
```

can be 

```elisp
(lambda (&rest data)
  (org-jira-update-worklogs-for-current-issue))
```

**Comment by ahungry** [comment]
Thanks for finding this and bringing it up - this is ultimately due to how I incorrectly implemented the callback system awhile back when converting the package to be asynchronous.

```
         ELISP> (funcall (cl-function (lambda (&key data &allow-other-keys) (print data))) :data "Data" :foo "Foo")

         "Data"

         "Data"
         ELISP> (funcall (function (lambda (&key data &allow-other-keys) (print data))) :data "Data" :foo "Foo")
         *** Eval error ***  Wrong number of arguments: (lambda (&key data &allow-other-keys) (print data)), 4
```

The cl-function and allow-other-keys is correct - the refactor that I need to apply is to convert calls such as this (see, I used &rest instead of &key for data, woops):

```
         (defun org-jira-refresh-issue ()
           "Refresh issue from jira to org."
           (interactive)
           (ensure-on-issue
            (let* ((issue-id (org-jira-id))
                   (callback
                    (cl-function
                     (lambda (&rest data &allow-other-keys)
                       (message "org-jira-refresh-issue cb")
                       (org-jira-get-issues (list (cl-getf data :data)))))))
              (jiralib-get-issue issue-id callback))))
```

to instead be of a form such as this:
```
         (defun org-jira-refresh-issue ()
           "Refresh issue from jira to org."
           (interactive)
           (ensure-on-issue
            (let* ((issue-id (org-jira-id))
                   (callback
                    (cl-function
                     (lambda (&key data &allow-other-keys)
                       (message "org-jira-refresh-issue cb")
                       (org-jira-get-issues (list data))))))
              (jiralib-get-issue issue-id callback))))
```

Basically - if I flip all those `&rest data` to `&key data` as they should have been, I can drop the cl-getf I was using to pull the data keyword from the rest list (the cl-function + allow-other-keys is needed as request.el callback may call the callback with more than a :data keyword argument).

**Comment by ahungry** [comment]
All fixed up in master now, &rest changed to &key
