### ISSUE TITLE
Big refactor/code cleanup: jiralib/org-jira integration

### ISSUE THREAD

**Issue by ahungry** [ahungry/org-jira#116]
I think a large refactor/rewrite of what we have between these two files would be beneficial.

What I'm thinking of is incorporating EIEIO to make a more CLOS like approach to handling each 'thing', with a common set of defmethods, such as 'to-jira', 'to-org', 'save-to-org', 'save-to-jira' etc., as currently it has a combination of alist, plist, and random positional based tuples/lists that handle how data is shuffled among endpoints.

Having more concrete types / classes would make it much easier for new maintainers to hop in and understand the scope of one 'thing' they are working on or changing.

**Comment by Fuco1** [comment]
I would advice to make this as gradual as possible instead of a big one-time rewrite (i.e. a branch opened for half a year).  Because things will become inconsistent and features will diverge.

I'll try to go over the code and rewrite some parts using more idiomatic org API.  I've hacked on org a lot so I know some tricks to make thigns simpler and faster.

**Comment by ahungry** [comment]
Good call, closing this one

**Comment by Fuco1** [comment]
Not to say that it can't be done.  I'm not so familiar with the code yet to say where to start, but maybe `libjira` would be a good place... to create objects for various api calls and somehow provide a bit nicer interface.

For example the constant use of `cl-function` really annoys me... unpacking that into a regular lambda with the data parsed and passed in would be quite sweet.
