### ISSUE TITLE
Customizable insertion template?

### ISSUE THREAD

**Issue by jwiegley** [ahungry/org-jira#157]
At the moment stories get inserted like this:

```
** TODO Story Title    *FOO_123*
:PROPERTIES:...
*** description: [[][FOO-123]]
  comments...
```

I would much rather see:

```
** TODO [[][FOO-123]] Story Title
:PROPERTIES:...
comments...
```

It seems that each of these details is some element of an "issue template". Can we make that template customizable?

**Comment by ahungry** [comment]
The big challenge to this is that the dataflow is bi-directional.  As such, the display structure of the data itself is also it's on disk storage mechanism (there isn't a hidden layer that keeps updates as a middleware between Jira and what the user sees in the org buffer).  If we omitted certain things like "description" or randomly position/remove elements, I think it might have a lot of potential for unexpected bugs (when I took over, the code was, and still is, a bit unorganized in various areas).

The code also has a lot of assumptions that certain elements are in a certain spot, and this spot will not change (mostly in the re-sync to jira type calls).

I think a great addition that would allow this type of change (and a lot of others that people have asked for, such as sync items to buffers in different ways) would be to update the architecture to more closely resemble something like:

Jira <--> Persistence Layer (sqlite or elisp/json to disk etc.) <--> Org "view" layer 

Where the persistence layer stores some combination of Jira+Org data (so instead of an entire org section ever requiring parsing for pushing a jira update, just one "thing" at a time in the section would have to be mapped out, without being impactful to the other things).

This would be a lot of work for marginal gain though.

**Comment by Fuco1** [comment]
As John I also want the task number at the front of the issue.  I wrote this code to do that:

```elisp
(defun my-org-jira-add-issue-id-to-headline (Issue)
  (ensure-on-issue-id (oref Issue issue-id)
    (save-excursion
      (org-back-to-heading t)
      (org-beginning-of-line)
      (insert (org-jira-get-issue-key (oref Issue issue-id)) " "))))

(advice-add 'org-jira--render-issue :after 'my-org-jira-add-issue-id-to-headline)
```

@ahungry This is also an example of where the macro broke (we spoke about this yesterday).

I think at least a template for the header would be great since advice mechanism isn't the most stable across updates.

**Comment by bhipple** [comment]
I have a similar issue: I see it's inserting 2 spaces before every line, which seems to be done for sensible reasons:

```
;;  Insert 2 spaces of indentation so Jira markup won't cause org-markup
(org-jira-insert
  (replace-regexp-in-string
  "^" "  "
  (format "%s" (slot-value Issue heading-entry)))))))
```
This makes it really strange to view and edit text in the buffer, though, and tools like my word wrapping don't "just work", because they strip or mess up the leading spaces.  I tried monkey patching away this behavior but it seems to strongly prefer it; am I missing another place where we parse the leading whitespace?  I'm willing to deal with buggy edge cases where Jira syntax messes with org, in order to have a smoother common use case.

**Comment by ahungry** [comment]
If anyone wants to PR this, it'd certainly be a nice addition.
