### ISSUE TITLE
jira story type  can not be update or progress

### ISSUE THREAD

**Issue by clojurians-org** [ahungry/org-jira#16]
when i update the priority from Medium to Low, it didn't take affect.
when i progress the story, it show Wrong type argument: listp, 116.
i wonder whether it can show all comment so that i can update someone.

i can add comment and create new issue successfully.

my org-jira version is:
~/.emacs.d/elpa/org-jira-20161215.2310

**Comment by clojurians-org** [comment]
Leaving directory `/home/spiderdt/.emacs.d/elpa/org-jira-20161215.2310'                                                                   
^L                                                                                                                                        
Compiling file /home/spiderdt/.emacs.d/elpa/org-jira-20161215.2310/jiralib.el at Mon Dec 19 01:08:51 2016                                 
Entering directory `/home/spiderdt/.emacs.d/elpa/org-jira-20161215.2310/'                                                                 
                                                                                                                                          
In jiralib-call:                                                                                                                          
jiralib.el:287:11:Warning: reference to free variable `jiralib-issue-regexp'                                                              
jiralib.el:295:15:Warning: assignment to free variable `jiralib-issue-regexp'                                                             
jiralib.el:307:54:Warning: function `coerce' from cl package called at runtime                                                            
                                                                                                                                          
In jiralib--rest-call-it:                                                                                                                 
jiralib.el:384:8:Warning: jiralib--rest-call-it being defined to take 1+ args,                                                            
    but was previously called with 0-5                                                                                                    
                                                                                                                                          
In end of data:                                                                                                                           
jiralib.el:941:1:Warning: the function `org-jira-find-value' is not known to                                                              
    be defined.                                                                                                                           
^L                                                                                                                                        
Compiling file /home/spiderdt/.emacs.d/elpa/org-jira-20161215.2310/org-jira-autoloads.el at Mon Dec 19 01:08:51 2016                      
^L                                                                                                                                        
Compiling file /home/spiderdt/.emacs.d/elpa/org-jira-20161215.2310/org-jira-pkg.el at Mon Dec 19 01:08:51 2016                            
^L                                                                                                                                        
Compiling file /home/spiderdt/.emacs.d/elpa/org-jira-20161215.2310/org-jira.el at Mon Dec 19 01:08:51 2016                                
                                                                                                                                          
In org-jira-get-projects:                                                                                                                 
org-jira.el:358:30:Warning: assignment to free variable `p'                                                                               
org-jira.el:358:36:Warning: reference to free variable `p'                                                                                
                                                                                                                                          
In org-jira-insert:                                                                                                                       
org-jira.el:386:32:Warning: `default-buffer-file-coding-system' is an obsolete                                                            
    variable (as of 23.2); use `buffer-file-coding-system' instead.                                                                       
org-jira.el:545:12:Error: Garbage following &rest VAR in lambda-list                                                                      
^L                                                                                                                                        
Compiling no file at Mon Dec 19 01:09:39 2016

**Comment by ahungry** [comment]
Thanks for the report.

Do you know what version of Emacs you're using and what version of Jira your server is running?

Are you using the new REST mode for org-jira or the old SOAP mode?

The SOAP mode will be pretty unmaintained as Jira no longer supports it and I don't have a legacy Jira instance to test against it with (when it makes sense to, I'll probably remove the SOAP portions from org-jira and possibly make a new org-jira-soap or org-jira-legacy package).

**Comment by clojurians-org** [comment]
i use GNU Emacs 24.5.1,
and i set the url to (setq jiralib-url "https://spiderdata.atlassian.net"),
then i use the 
usename: larluo@spiderdt.com, 
password: spiderdt.com 
to look up related info.

then i use org-mode, and org-jira-mode to get project and issues.

**Comment by ahungry** [comment]
Thanks, I'll work on debugging this tonight.  It could be related to the deadline/duedate integration commit or the recent dynamically populating issue types (based on project vs plain issue type list).

If you add this to your ~/.emacs (or set it before running the org-jira functions) do you still experience the problem?

    (setq org-jira-deadline-duedate-sync-p nil)

**Comment by ahungry** [comment]
Can you let me know what your Jira says when you set up request.el debug as such?

    (setq request-log-level 'debug)
    (setq request-message-level 'debug)

And the update fails?

**Comment by ahungry** [comment]
Make sure to test with tonight's changes as well, in case any of the cleanup fixed your problem.

**Comment by palashkulsh** [comment]
Hi ahungry
I'm facing the exact same problem. I'm using org mode 9.0.8 . on running org-jira-update-issue. It doesn't change the issue priority.Can you please help whenever you can.

**Comment by noiseOnTheNet** [comment]
Hi, same problem here with GNU Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-05-16 on KAEL

REQUEST [debug] REQUEST
REQUEST [debug] Run: curl --silent --include --location --compressed --cookie c:\Users\mvezzoli\.emacs.d\request\curl-cookie-jar --cookie-jar c:\Users\mvezzoli\.emacs.d\request\curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective %{url_effective}) --header Authorization: Basic bXZlenpvbGk6MjAxN0VsZW5h --header Content-Type: application/json https://jira.micron.com/jira/rest/api/2/issue/RNDRELDA-12/transitions
REQUEST [debug] REQUEST--CURL-CALLBACK event = finished

REQUEST [debug] REQUEST--CURL-CALLBACK proc = #<process request curl>
REQUEST [debug] REQUEST--CURL-CALLBACK buffer = #<buffer  *request curl*>
REQUEST [debug] REQUEST--CURL-CALLBACK symbol-status = nil
REQUEST [debug] REQUEST--CALLBACK
REQUEST [debug] (buffer-string) =
HTTP/1.1 200 OK

Date: Tue, 10 Oct 2017 07:33:11 GMT

Server: Apache-Coyote/1.1

X-AREQUESTID: 93x84357765x140

X-ASESSIONID: ovdycs

X-ASEN: SEN-2793298

X-Seraph-LoginReason: OK

X-AUSERNAME: MVEZZOLI

Cache-Control: no-cache, no-store, no-transform

X-Content-Type-Options: nosniff

Content-Type: application/json;charset=UTF-8

Connection: close

Transfer-Encoding: chunked



{"expand":"transitions","transitions":[{"id":"101","name":"Evaluate","to":{"self":"https://jira.micron.com/jira/rest/api/2/status/10074","description":"Evaluating a task, new feature request, story, bug etc to determine the root cause, or for scoping etc.","iconUrl":"https://jira.micron.com/jira/images/icons/statuses/generic.png","name":"Evaluating","id":"10074","statusCategory":{"self":"https://jira.micron.com/jira/rest/api/2/statuscategory/4","id":4,"key":"indeterminate","colorName":"yellow","name":"In Progress"}}},{"id":"121","name":"Start Work","to":{"self":"https://jira.micron.com/jira/rest/api/2/status/3","description":" ","iconUrl":"https://jira.micron.com/jira/images/icons/statuses/inprogress.png","name":"In Progress","id":"3","statusCategory":{"self":"https://jira.micron.com/jira/rest/api/2/statuscategory/4","id":4,"key":"indeterminate","colorName":"yellow","name":"In Progress"}}},{"id":"161","name":"Hold","to":{"self":"https://jira.micron.com/jira/rest/api/2/status/1","description":" ","iconUrl":"https://jira.micron.com/jira/images/icons/statuses/open.png","name":"Open","id":"1","statusCategory":{"self":"https://jira.micron.com/jira/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"To Do"}}},{"id":"71","name":"Close","to":{"self":"https://jira.micron.com/jira/rest/api/2/status/6","description":" ","iconUrl":"https://jira.micron.com/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://jira.micron.com/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}}}]}
REQUEST [debug] REQUEST-RESPONSE--CANCEL-TIMER
REQUEST [debug] -CLEAN-HEADER
REQUEST [debug] -CUT-HEADER
REQUEST [debug] error-thrown = nil
REQUEST [debug] -PARSE-DATA
REQUEST [debug] parser = json-read
REQUEST [debug] data = ((transitions . [((to (statusCategory (name . In Progress) (colorName . yellow) (key . indeterminate) (id . 4) (self . https://jira.micron.com/jira/rest/api/2/statuscategory/4)) (id . 10074) (name . Evaluating) (iconUrl . https://jira.micron.com/jira/images/icons/statuses/generic.png) (description . Evaluating a task, new feature request, story, bug etc to determine the root cause, or for scoping etc.) (self . https://jira.micron.com/jira/rest/api/2/status/10074)) (name . Evaluate) (id . 101)) ((to (statusCategory (name . In Progress) (colorName . yellow) (key . indeterminate) (id . 4) (self . https://jira.micron.com/jira/rest/api/2/statuscategory/4)) (id . 3) (name . In Progress) (iconUrl . https://jira.micron.com/jira/images/icons/statuses/inprogress.png) (description .  ) (self . https://jira.micron.com/jira/rest/api/2/status/3)) (name . Start Work) (id . 121)) ((to (statusCategory (name . To Do) (colorName . blue-gray) (key . new) (id . 2) (self . https://jira.micron.com/jira/rest/api/2/statuscategory/2)) (id . 1) (name . Open) (iconUrl . https://jira.micron.com/jira/images/icons/statuses/open.png) (description .  ) (self . https://jira.micron.com/jira/rest/api/2/status/1)) (name . Hold) (id . 161)) ((to (statusCategory (name . Done) (colorName . green) (key . done) (id . 3) (self . https://jira.micron.com/jira/rest/api/2/statuscategory/3)) (id . 6) (name . Closed) (iconUrl . https://jira.micron.com/jira/images/icons/statuses/closed.png) (description .  ) (self . https://jira.micron.com/jira/rest/api/2/status/6)) (name . Close) (id . 71))]) (expand . transitions))
REQUEST [debug] symbol-status = success
Wrong type argument: listp, 116

**Comment by yisraeldov** [comment]
Also having this issue

**Comment by ahungry** [comment]
This doesn't occur when using the current cloud Jira and latest org-jira package under GNU/Linux Arch Linux / Emacs 27.0.50, so someone having this issue is going to need to work on a fix, as it isn't really possible for me to simulate setups outside my own at this time.

If anyone can pitch in, it would be great!
