### ISSUE TITLE
org-jira-update-issue: cannot update reporter

### ISSUE THREAD

**Issue by babariviere** [ahungry/org-jira#181]
When calling org-jira-update-issue to update description (not reporter), I got the following response from Jira:
```
{"errorMessages":[],"errors":{"reporter":"Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown."}}
```

Is there a way to update description without updating properties ?

**Comment by ahungry** [comment]
https://github.com/ahungry/org-jira/issues/102

Maybe related - so, in your Jira instance, "Reporter" isn't a field on your issues?  To me, it seems like Reporter and Assignee would be standard on all tickets, but I guess we need to make this property optional.

org-jira-update-issue-details is the function that is updating this value

**Comment by babariviere** [comment]
I can set reporter and assignee with Jira UI. I thinks the problem is with API call on Jira endpoint.

**Comment by makuto** [comment]
I'm not speaking from authority, but I think that you might need an administrator account in order to update the reporter. I don't have those permissions at my work.

As a workaround I commented the lines with `org-issue-reporter` in `org-jira-update-issue-details`, which makes updating work for me.

Does anyone know for sure whether it is a permissions issue? If it is, is there some way we could check for the permission and only send the field if the user has that permission?

**Comment by nickgarber** [comment]
Hi, I contributed the ability to set reporter. I've always had admin privs on Jira instances I use so the requirement of elevated permissions was a blind-spot for me.

As a correction, I'd like to make the change @makuto described the norm, then perhaps later it could be moved behind a `customize` feature gate.

I use this functionality often, but it's always via `C-c isr`, (aka `org-jira-set-issue-reporter`), which will  continue to work as it already does for those who'd like to use it.

**Comment by ahungry** [comment]
The new defcustom `jiralib-update-issue-fields-exclude-list` could exclude it now.
