### ISSUE TITLE
org-jira-get-assignable-users doesn't retrieve all users

### ISSUE THREAD

**Issue by utrack** [ahungry/org-jira#195]
(o-j-g-a-u) returns only part of users in our Jira - I can't find many people including myself.

`(length (org-jira-get-assignable-users nil))` returns 1002 - looks like there's pagination that's ignored by the module.

**Comment by nardusg** [comment]
Hi

Did you manage to fix this or did you found a work around ?

Thanks

**Comment by utrack** [comment]
Nope, not really - I haven't touched org-jira in a long time. I'll try again soon and report progress if I'll have any.

**Comment by nardusg** [comment]
can help test, user total is above 10 000 😱

**Comment by ahungry** [comment]
The code is hardcoded as such for the "getUsers" call in jiralib.el:

"/rest/api/2/user/assignable/search?project=%s&maxResults=10000"

Where project will be the project key of your current project - i'll have to cross reference this call against the API docs, because I don't have a jira set up atm with > 10000 users.

**Comment by ahungry** [comment]
There is also this endpoint which the assignable one seems to recommend:

"/rest/api/2/users/search/?maxResults=10000"

The jira v2 api documentation does say the assignable/search has a cap of 1000 users.

I'd be open to a PR to fix this.  

Does your Jira partition users at all?  It seems odd to have a potential pool of over 1000 people to assign a task to (usually this would be a subset of the total jira users, based on who is actually assignable to a given task for a given project id).

**Comment by nardusg** [comment]
We use LDAP to an AD. I can check if it is partitioned, no idea.

This is what I get when it want to assing anybody:

![Screenshot-2020-05-26-183233-172x313](https://user-images.githubusercontent.com/29011858/82926296-49709780-9f7f-11ea-9686-5de2c0ddf323.png)

**Comment by ahungry** [comment]
Judging by your screenshot, this is also hitting a problem with another issue regarding jira switching from showing usernames to using opaque id values that supersede what it used to do (show usernames).

When you use the jira GUI for your instance and go to assign a ticket, does it include a list of more than 1000 people as potential assignees?  That seems an odd jira setup, since it'd seem hard to manage tickets divided among > 1000 people (for instance, if I can assign a ticket, it would be limited to a small pool of people who are actually qualified to work said ticket, based on project etc).

**Comment by nardusg** [comment]
It looks like a weird setup indeed. I can scroll down and it refresh forever. The readable usernames only appear at the end. They did do an upgrade from an old version, might have broken something.

![Screenshot from 2020-05-27 05-21-12](https://user-images.githubusercontent.com/29011858/82974835-2d024880-9fdb-11ea-93ed-cf7a3f1390a3.png)

**Comment by nardusg** [comment]
Found the issue, possible assigned persons was the whole user base, changed the permissions to my group and now it is all good.
