### ISSUE TITLE
Why 2 repos?

### ISSUE THREAD

**Issue by nevetS** [ahungry/org-jira#196]
Searching for this I see:  https://github.com/baohaojun/org-jira and I see that repo referenced on the emacs wiki: https://www.emacswiki.org/emacs/OrgJiraMode#toc3

Both have the same melpa link in the readme.

This project looks to be the owner in Melpa.

1.  I'd like to confirm that this is the official repository for org-jira
2.  If so, the emacs wiki should be updated
3.  Is there history here?  Is this a fork of a project that went un-maintained?

**Comment by ahungry** [comment]
This is the one linked to melpa, @baohaojun  kindly passed the torch to this repo (initially I did not use github fork and instead re-launched the code as a non-fork, because iirc, at the time, the other one was unmaintained and I wanted to alleviate confusion by not showing up as a fork of some other repo that was hundreds of commits behind)

**Comment by ahungry** [comment]
I don't have an emacswiki account - does someone that does have the time to update it?

**Comment by baohaojun** [comment]
I will update the emacswiki:D

**Comment by Rovanion** [comment]
The URL has been changed on emacs-wiki. I believe anyone can edit it without an account, I atleast think that I just did.

**Comment by nicosierra** [comment]
I'd suggest to add a reference to the prior maintainer in the README as well.
It gives him/her the proper credits, and clarifies end users the reason why there are two repositories with the same name.

**Comment by ahungry** [comment]
Sure, go ahead and add it to the readme via PR, it'd be a welcome addition.
