### ISSUE TITLE
Working on issues with other people

### ISSUE THREAD

**Issue by robs-nice99** [ahungry/org-jira#234]
Hello!

I'm now working in JIRA issues with other team elements. However, when I run `org-jira-get-issue` it gets all the time logged by my colleagues and then, org-mode clock tables includes all the time, from me an d my collegues.

Also, when updating times (`org-jira-update-worklog`) it seems all existing time logs are updated as if they were mine.

How can I avoid this, so I can track only my time?

Thanks!

**Comment by ahungry** [comment]
You may have to make a PR to adjust the handling of this, as it's outside of my use cases at the moment and I don't have a reliable way to test the scenario.

**Comment by nickgarber** [comment]
Hi @robs-nice99! 
I used the worklog import filter feature to "fix" this in my setup. 

```emacs-lisp
;; use-package example
(use-package org-jira
  :after (org)
  :bind
  (:map org-jira-entry-mode-map
	("C-c i g" . org-jira-get-issue)
	("C-c i G" . org-jira-get-issues)
	("C-c i s r" . org-jira-set-issue-reporter))
  :custom
  (jiralib-worklog-import--filters-alist
   '((t "WorklogAuthoredByCurrentUser"
	(lambda (wl) (let-alist wl
		       (when
			   (and wl
				(string-equal
				 (downcase
				  (or jiralib-user-login-name user-login-name))
				 (downcase \.author\.name)))
			 wl))))))
  :config
  (setq org-jira-custom-jqls '(:jql "assignee = currentUser() and sprint in openSprints()" :limit 100 :filename "taskview-personal-SprintWork")))
```

or more simply
```emacs-lisp
(add-to-list 'jiralib-worklog-import--filters-alist
   '(t "WorklogAuthoredByCurrentUser"
	(lambda (wl) (let-alist wl
		       (when
			   (and wl
				(string-equal
				 (downcase
				  (or jiralib-user-login-name user-login-name))
				 (downcase \.author\.name)))
			 wl)))))
```
This works by filtering-out worklogs created by other people before they're pulled into an issue. Since `org-jira`'s update actions are only applied to worklogs present in the Org property drawer, this import filter has the convenient effect of ensuring that only worklogs created by the logged in user are ever updated/changed in any way.

This might be considered a work-around but it's worked well for me, so wanted to pass it along!

This is likely to work for you as long as you don't also need for the worklogs from other folks to still show up in their respective issues.

**Comment by ahungry** [comment]
Thanks for the code @nickgarber !  I think it may be worth including as a default setting - I doubt many people actually relied on / preferred the previous behavior (for me, I simply had no test data sets to work on my worklogs vs other's worklogs).

**Comment by ahungry** [comment]
Oh, the code itself isn't custom, just setting the defcustom value from nil to t.

Users can set this via:

M-x customize-variable
jiralib-worklog-import--filters-alist

Then toggle both to "on".

I may still flip the default from nil to t, so users can turn off these filters, but they'd be enabled as the default.
