### ISSUE TITLE
Invalid JSON produced for component list.

### ISSUE THREAD

**Issue by cameron1729** [ahungry/org-jira#27]
Hi, thanks for this awesome project.

On emacs 25.4.1 I am noticing that the structure generated for the component list does not properly get converted to JSON, which stops several update operations. I'm not sure if it's something weird about my set up, since I would imagine others would have hit this issue too...

The first problem is that out of the box it produces a list like: `(components (id . comp-id) (id . item))` - i.e., `comp-id` and `item` are never evaluated. The second problem is that json-encode converts this to an object, i.e., `{"components": {"id":"comp-id", "name": "item"}, ....` when jira's rest api wants it as an array of objects, i.e., `{"components": [{"id":"comp-id", "name": "item"}], ....`

**Comment by ahungry** [comment]
Thanks!

**Comment by ahungry** [comment]
I had to revert this commit, as Emacs 25.1.1 fails to update issues or comments when it is in place (an error about the pushed data not being an array).  I'll have to take a closer look into what may be your issue.

**Comment by ahungry** [comment]
So, I think the original fix was close, and likely needs only minor adjustment - you're right, the reason it worked previously is simply that it's evaluating that components block to be `(components . [])`, instead of something useful.

When your commit is in place, this becomes (on my instance) a single value, `(components)`, which isn't correct either (as I don't have any components associated with my project).

**Comment by ahungry** [comment]
@cameron1729 take a look at tag 2.5.4 or commit here: https://github.com/ahungry/org-jira/commit/d7cd4d9c9b44c9460beb2b6b0aeb6cff41d9b6ca this re-adds your fix, and handles the case where components are nil / empty.
