### ISSUE TITLE
Can only fetch issues, not create

### ISSUE THREAD

**Issue by worldofgeese** [ahungry/org-jira#274]
I've tried with both basic auth and the cookie workaround and in both cases I can fetch issues but not create them. When I attempt to create an issue I get:

```
[error] request--callback: peculiar error: 404

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/user"

(:params ((accountId . "account-id")))

"JIRA_ERROR RESPONSE: "

((errorMessages . ["Specified user does not exist or you do not have required permissions"]) (errors))

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
[error] request--curl-sync: semaphore never called
[error] request--callback: peculiar error: 400

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/issue"

(:type "POST" :data "{\"fields\":{\"project\":{\"key\":\"IN\"},\"parent\":{\"key\":null},\"issuetype\":{\"id\":\"10292\"},\"summary\":\"Remove floating IPs from MetaKube\",\"description\":\"\",\"priority\":{\"id\":\"10001\"},\"assignee\":{\"accountId\":null}}}")

"JIRA_ERROR RESPONSE: "

((errorMessages . []) (errors (priority . "Field 'priority' cannot be set. It is not on the appropriate screen, or unknown.")))

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
[error] request--curl-sync: semaphore never called
jiralib--rest-call-it: jiralib--rest-call-it was called with a NIL api value.
```

I 'm running the latest org-jira as of today.

**Comment by ahungry** [comment]
It looks like you are setting the "priority" and lack permission to do so (or your endpoint does not have this field configured).

Look into: jiralib-update-issue-fields-exclude-list and try adding the `priority` symbol in there?

**Comment by worldofgeese** [comment]
Unfortunately, the error issues further back, before specifying priority as you can see here, after adding `priority` to `jiralib-update-issue-fields-exclude-list`:
```
[error] request--callback: peculiar error: 404

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/user"

(:params ((accountId . "account-id")))

"JIRA_ERROR RESPONSE: "

((errorMessages . ["Specified user does not exist or you do not have required permissions"]) (errors))
```

I can confirm I can fetch issues, so I'm unsure why it complains of my specified user not existing.

**Comment by worldofgeese** [comment]
Something like this?

```
(defcustom jiralib-update-issue-fields-exclude-list nil
  "A list of symbols to check for exclusion on updates based on matching key.
Key names should be one of components, description, assignee, reporter, summary, issuetype."
  :type '(set (const :tag "Exclude components" components)
              (const :tag "Exclude description" description)
              (const :tag "Exclude assignee" assignee)
              (const :tag "Exclude reporter" reporter)
              (const :tag "Exclude summary" summary)
              (const :tat "Exclude issue type" issuetype)
              (const :tag "Exclude priority" priority))
  :group 'org-jira)
(setq jiralib-update-issue-fields-exclude-list 'priority)
```

**Comment by ahungry** [comment]
Try:

`(setq jiralib-update-issue-fields-exclude-list '(priority))`

as it needs to be a list of symbols.

**Comment by worldofgeese** [comment]
Unfortunately, I now experience both full Emacs session freezes, which I can bail from with `C-g`. Messages buffer shows
```
Decrypting /home/worldofgeese/.authinfo.gpg...done
Fetching issues...
About to render 4 issues.
org-jira-update-worklogs-for-issue id: IN-328 filename: IN
Quit
org-jira-update-worklogs-for-issue cb id: IN-328 fn: IN
In the callback for org-jira-update-comments-for-issue.
```

When I bail `IN.org` becomes populated by one task. If I run fetch issues again, I will get another task but Emacs will freeze and no longer respond to `C-g`.

Attempting to create a task is also fruitless with you suggested `(setq jiralib-update-issue-fields-exclude-list '(priority))` as I continue to be queried for a task during task creation and run into errors both before and after the query for priority:

```
[error] request--callback: peculiar error: 404

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/user"

(:params ((accountId . "account-id")))

"JIRA_ERROR RESPONSE: "

((errorMessages . ["Specified user does not exist or you do not have required permissions"]) (errors))

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
[error] request--curl-sync: semaphore never called
[error] request--callback: peculiar error: 400

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/issue"

(:type "POST" :data "{\"fields\":{\"project\":{\"key\":\"IN\"},\"parent\":{\"key\":null},\"issuetype\":{\"id\":\"10292\"},\"summary\":\"test\",\"description\":\"tes\",\"priority\":{\"id\":\"10001\"},\"assignee\":{\"accountId\":\"60a41e425d67f200694a7ed1\"}}}")

"JIRA_ERROR RESPONSE: "

((errorMessages . []) (errors (priority . "Field 'priority' cannot be set. It is not on the appropriate screen, or unknown.")))

error in process sentinel: JIRA_ERROR - see your *Messages* buffer for more details. [2 times]
[error] request--curl-sync: semaphore never called
jiralib--rest-call-it: jiralib--rest-call-it was called with a NIL api value.
```

**Comment by TuxTom** [comment]
I have the same issue as the original one. From what I can see, the problem lies in `org-jira-get-assignable-users `. It tries to use the entry `accountId` from the struct that is returned by `jiralib-get-users`, which does not exist (at least for me). The username, which I assume is wanted, is contained as `key` and `name`, though.
(Sorry if I'm not using the right terms, I'm rather new to elisp. I hope you still get what I mean.)

**Comment by LeeRuns** [comment]
> Try:
> 
> `(setq jiralib-update-issue-fields-exclude-list '(priority))`
> 
> as it needs to be a list of symbols.
 
**How would I apply multiple symbols, _like this?_**


``` elisp
(setq jiralib-update-issue-fields-exclude-list '(
                                                                          (priority)
                                                                          (components)
)
```

**Comment by ahungry** [comment]
```
(setq jiralib-update-issue-fields-exclude-list '(priority components))
```

**Comment by 0l1ve** [comment]
I have also been experiencing this.  Though for me it appears to be a difference in the Jira Rest API's.  According to the JIra documentation the Cloud Rest API requires `accountID` when creating an issue.  However, this does not exist in the Server version of Jira, where the `name` field is used for assigning issues.

I just managed to fix this by adding a new defcust variable named `jiralib-cloud-enabled` and adding a couple of if statements to change the account portion of the rest call.  So if I set the variable to nil, then name is used instead of accountID, and vice-versa.  Not sure if this is specific to just me or not but below is the patch code showing what changes I ended up with.


`diff --git a/jiralib.el b/jiralib.el
index 1aaf0db..0fd6461 100644
--- a/jiralib.el
+++ b/jiralib.el
@@ -188,6 +188,12 @@ The default value works if JIRA is located at a hostname named
   :type 'integer
   :group 'jiralib)
 
+(defcustom jiralib-cloud-enabled
+  t
+  "If enabled then cloud restAPI calls will be made"
+  :type 'boolean
+  :group 'jiralib)
+
 (defvar jiralib-token nil
   "JIRA token used for authentication.")
 
diff --git a/org-jira.el b/org-jira.el
index b631f71..0ef7f80 100644
--- a/org-jira.el
+++ b/org-jira.el
@@ -622,11 +622,17 @@ it isn't already on."
   (append
    '(("Unassigned" . nil))
    org-jira-users
-   (mapcar (lambda (user)
-             (cons (org-jira-decode (cdr (assoc 'displayName user)))
-                   (org-jira-decode (cdr (assoc 'accountId user)))))
-           (jiralib-get-users project-key))))
-
+   (if jiralib-cloud-enabled 
+       ((mapcar (lambda (user)
+                  (cons (org-jira-decode (cdr (assoc 'displayName user)))
+                        (org-jira-decode (cdr (assoc 'accountId user)))))
+                (jiralib-get-users project-key)))
+     (mapcar (lambda (user)
+               (cons (org-jira-decode (cdr (assoc 'displayName user)))
+                     (org-jira-decode (cdr (assoc 'name user)))))
+             (jiralib-get-users project-key)))
+   ))
+   
 (defun org-jira-get-reporter-candidates (project-key)
   "Get the list of assignable users for PROJECT-KEY, adding user set jira-users first."
   (append
@@ -1767,7 +1773,8 @@ that should be bound to an issue."
           (equal type "")
           (equal summary ""))
       (error "Must provide all information!"))
-  (let* ((project-components (jiralib-get-components project))
+  (if jiralib-cloud-enabled
+      (let* ((project-components (jiralib-get-components project))
          (jira-users (org-jira-get-assignable-users project))
          (user (completing-read "Assignee: " (mapcar 'car jira-users)))
          (priority (car (rassoc (org-jira-read-priority) (jiralib-get-priorities))))
@@ -1786,7 +1793,27 @@ that should be bound to an issue."
              (priority (id . ,priority))
              ;; accountId should be nil if Unassigned, not the key slot.
              (assignee (accountId . ,(or (cdr (assoc user jira-users)) nil)))))))
-    ticket-struct))
+        ticket-struct)
+    (let* ((project-components (jiralib-get-components project))
+           (jira-users (org-jira-get-assignable-users project))
+           (user (completing-read "Assignee: " (mapcar 'car jira-users)))
+           (priority (car (rassoc (org-jira-read-priority) (jiralib-get-priorities))))
+           (ticket-struct
+            `((fields
+               (project (key . ,project))
+               (parent (key . ,parent-id))
+               (issuetype (id . ,(car (rassoc type (if (and (boundp 'parent-id) parent-id)
+                                                       (jiralib-get-subtask-types)
+                                                     (jiralib-get-issue-types-by-project project))))))
+               (summary . ,(format "%s%s" summary
+                                   (if (and (boundp 'parent-id) parent-id)
+                                       (format " (subtask of [jira:%s])" parent-id)
+                                     "")))
+               (description . ,description)
+               (priority (id . ,priority))
+               ;; accountId should be nil if Unassigned, not the key slot.
+               (assignee (name . ,(or (cdr (assoc user jira-users)) nil)))))))
+      ticket-struct)))
 
 ;;;###autoload
 (defun org-jira-create-issue (project type summary description)
`

**Comment by LeeRuns** [comment]
bump :)

**Comment by ahungry** [comment]
Thanks for the bump @LeeRuns, but what do you think is the issue we should look into regarding this?

I think we've got two things in this thread - training regarding usage of jiralib-update-issue-fields-exclude-list, and a cloud vs server issue.

@0l1ve kindly linked their fork with server support here: https://github.com/ahungry/org-jira/issues/287 - however I have some reservations about it (mentioned in that thread).

In any case, I think this issue should probably be closed - there isn't anything to do with the var that I can see, and the other thread should take precedence for that issue.
