### ISSUE TITLE
Unable to unassign issue

### ISSUE THREAD

**Issue by msherry** [ahungry/org-jira#283]
When trying to call `org-jira-unassign-issue` on an issue, I get an error, and see the following output in the `*Messages*` buffer:

```
[error] request--callback: peculiar error: 400

"JIRA_ERROR - see your *Messages* buffer for more details."

"JIRA_ERROR REQUEST: "

"/rest/api/2/issue/XXX-971"

(:type "PUT" :data "{\"fields\":{\"components\":[],\"priority\":{\"id\":\"10000\",\"name\":\"Default\"},\"description\":\"Ensure that Jarvis can be used to perform actions (block/unblock, bypass, add labels, etc.)\",\"assignee\":{\"id\":null},\"reporter\":{\"id\":null},\"summary\":\"Jarvis actions\",\"issuetype\":{\"id\":\"7\",\"name\":\"Story\"}}}")

"JIRA_ERROR RESPONSE: "

((errorMessages . []) (errors (assignee . "expected Object containing a 'name' property")))
```

I'm running the latest org-jira as of today, via Melpa.

**Comment by ahungry** [comment]
`\"assignee\":{\"id\":null},\"reporter\":{\"id\":null},` - I'm guessing it doesn't like this - it may be a byproduct of some translation logic between the old shortnames [~mcarter] for instance, and the new UUIDs which store names, or this issue has been present for some time and just rarely gets encountered.

I'll have to look up what the input for unassigning is supposed to be - I don't think it'd be a "name" property as the error message states, since the whole point is to have no name assigned.

**Comment by ahungry** [comment]
There was a different fix that I made in the last couple months to address the unassigned assignee scenario - I'm going to close this one out due to age for now - I don't think this is a common/current issue (pertaining to latest version cloud users at least).
