### ISSUE TITLE
Worklogs?

### ISSUE THREAD

**Issue by LeeRuns** [ahungry/org-jira#285]
Could you provide some documentation on the worklog tracking feature? I got it to fetch and update issues but not able to get any of my clocks to go anywhere.

**Comment by ahungry** [comment]
What happened when you ran:

`(define-key org-jira-map (kbd "C-c wu") 'org-jira-update-worklogs-from-org-clocks)`

Did it give an error?

Normally I just use that key combo, when the cursor is on the entry, and it'll push my worklogs to Jira, receive the internal jira worklog/time entry id, and refresh the worklog view in my org buffer to show said new id.

**Comment by LeeRuns** [comment]
Well, I got that to work, but now am having problems pulling down all of my issues.
it stops at 50 and have not figured out how to get more yet.

**Comment by LeeRuns** [comment]
made a bit of progress by reading through some of the code. But can't push issues because my jira doesn't use "priority" Is there a way to prevent this during the creation of a new task or subtask? 
This causes the rest post to fail

**Comment by ahungry** [comment]
Check out the resolution here: https://github.com/ahungry/org-jira/issues/276 

If your Jira is missing certain expected fields, you can customize to omit/ignore them via the defcustom that is referenced there.

A limit of 50 sounds like a pagination issue - I personally just prefer more fine-tuned queries using the custom-jql features (search readme for "jql") - then you can refine your searches so that you aren't trying to pull more than 50 issues at a time - even if you up the jira pagination limit in this package, it's possible you can still encounter some server side pagination limits.
