### ISSUE TITLE
Moving jiralib to a separate package

### ISSUE THREAD

**Issue by elken** [ahungry/org-jira#308]
Thanks for the great package!

I'm looking at working on my own jira package and it would be _great_ if jiralib could be hoisted into its own package. What are the chances of this happening soon, if at all?

**Comment by ahungry** [comment]
I think you could just depend on org-jira and use it as it is (`(require 'jiralib)`)?

Someone else (you?) is welcome to fork it (notice it has some dependency on org-jira-sdk.el), but I probably won't be doing this work. It would be harder to maintain org-jira, and last time I tried to do anything on MELPA (whether adding a new package or even a single new file, ala org-jira-sdk) I felt like it was too much ceremony to want to go through it again (unless I'm feeling extra ambitious :smile: ).

I've had a long term idea of making a platform agnostic "ticketlib" where the org-jira features would work with many different back ends (jiralib, a github issue lib, some FOSS ticket solutions etc.)

**Comment by elken** [comment]
I mean yeah I could, but it seems a bit silly to have to include the whole thing to just use a few of the functions.

A platform-agnostic ticketlib does sound quite cool though! Hopefully this comes to fruition.

As for the melpa ceremony, it's quite trivial now; one just has to create a recipe file. 

I'd be willing to add jiralib as a melpa recipe (is jiralib.el all you need?) on your behalf if you'd be able to assist on any issues that arise on meeting their standards of licensing etc?

**Comment by ahungry** [comment]
While most my interactions with MELPA (team) have been cordial, it's **far** from just needing a recipe file.

I believe 100% of my packages have undergone scrutiny by multiple reviewers before the request for inclusion was honored (except for, ironically, org-jira - as I was bestowed the maintainer mantle from the old author due to abandonment).

I actually doubt jiralib.el (as is) would be up to snuff under the existing (or at least circa 2019) review process.

https://github.com/melpa/melpa/pulls?q=is%253Apr+author%253Aahungry+is%253A

Maybe I have some long-held resentment towards being "forced" to include docstrings that I saw little value in :laughing: 

So yea, the short answer is "no" for now.
