### ISSUE TITLE
Problem with org-jira-update-worklogs-from-org-clocks

### ISSUE THREAD

**Issue by lelit** [ahungry/org-jira#319]
Hi! 

I'm trying to take advantage of this nice package to make it easier for me to upload _worklogs_ to Jira, but it seems I'm missing some critical step.

I was able to configure `org-jira` to access the Jira instance, and then to download my issues using `org-jira-get-issues`, obtaining a file `PROJ.org` containing them under the configured `org-jira-working-dir`.

At that point I copied the `LOGBOOK` table of one issue (say "PROJ-42") from another Org file I use to track my work into the corresponding issue in `PROJ.org` and invoked `org-jira-update-worklogs-from-org-clocks`: at that point, it created an **empty** file `PROJ-42.org` under `org-jira-working-dir` and raised an error saying 
```
org-jira-update-worklogs-from-org-clocks: Issue PROJ-42 not found!
```

I then copied whole `PROJ-42` subtree from `PROJ.org` to that `PROJ-42.org` file, and re-executing `org-jira-update-worklogs-from-org-clocks` from there it worked as expected, updating the issue on the Jira instance **and** reporting back the `IDs` of each worklog into the `LOGBOOK` table of `PROJ-42.org`. :trophy:!

I digged into `org-jira.el` following the code path but could not find what I am missing: that function [calls](https://github.com/ahungry/org-jira/blob/master/org-jira.el#L1332) `ensure-on-issue-id-with-filename` passing it the ID of the issue **and** a filename, computed by `org-jira-filename` that indeed is `"PROJ-42"`. In turn, that `ensure-on-issue-id-with-filename` [tries](https://github.com/ahungry/org-jira/blob/master/org-jira.el#L452) to select an existing buffer visiting that filename or loads it if there is none, then finds the issue and does a `org-narrow-to-subtree`. So, IIUC, it effectively relies on the presence of that _issue specific_ orgfile, it ignores the `PROJ.org` created by `org-jira-get-issues`...

What am I'm doing wrong? Am I supposed to manually split that `PROJ.org` into individual orgfiles, with a single issue each?

Thanks in advance for any hint!

**Comment by ahungry** [comment]
This sounds awfully similar to the same core issue as https://github.com/ahungry/org-jira/issues/316 and here https://github.com/ahungry/org-jira/issues/314 

I did make an update to an unrelated issue around the time of the first ticket being filed, but I don't think 13457755932565306f42074c69076759a428568a is the cause of a regression, as that segment of code doesn't hit these same code paths.

There was an issue in that issue though, that noted a problem where some of `org` accessors to get at property values wasn't performing correctly unless the entire org-jira.el buffer was re-evaluated - I don't know if this is some change related to org / caching on the elc or eln files.

Thinking about it, it may be related - if it was trying to pull the `:FILENAME:` property and failing to get any result, it might be falling into some default behavior of making a new buffer named after the ticket itself...

Maybe I should push a change that reproduces the org accessor behavior and does a hard fail/error message when it gets a nil value - that way (at the least) we can have specialized logging around when this happens.

**Comment by ahungry** [comment]
Yea, reading the follow up here - https://github.com/ahungry/org-jira/issues/296 - I think this is all related to something external to this package - we shouldn't need to re-evaluate the org-jira.el and jiralib.el buffers on each usage for correct behavior - I couldn't reproduce the failure that was noted myself (the single re-eval fixed it), but I'll try again.

@lelit if you move the cursor over an entry and try something like ` (org-jira-get-issue-val-from-org 'filename)` - do you receive a value equal to your project+ticket id?  like `PROJ-42` instead of the value stored in `:filename:`?

**Comment by ahungry** [comment]
I just tried and confirm I get the value of the `:ID:` segment in the property block (the ticket id as noted), regardless of which accessor slot I try to get access to - let me try to find a fix that doesn't involve re-evaluation of the source buffer...

**Comment by ahungry** [comment]
This is me rubber-ducking a little bit... it's super strange though, on a re-eval of just this function, everything works as usual, but if I re-launch Emacs, I can see it doing strange behavior in the code flow if I add print debugging (since edebug won't work, due to the re-eval):
```
(t
           (org-jira-log (format "Our key is currently..."))
           (print key)
           (when (symbolp key)
             (org-jira-log "The key symbolp check was hit")
             (setq key (symbol-name key)))

           (setq key (or (assoc-default key org-jira-property-overrides) key))

           (org-jira-log (format "Our key is now: %s" key))

           (when (string= key "key")
             (org-jira-log "The key string= check was hit")
             (setq key "ID"))

           (org-jira-log (format "Second time - Our key is now: %s" key))
           ;; The variable `org-special-properties' will mess this up
           ;; if our search, such as 'priority' is within there, so
           ;; don't bother with it for this (since we only ever care
           ;; about the local properties, not any hierarchal or special
           ;; ones).
           (let ((org-special-properties nil))
             (org-jira-log (format "Final inner point - Our key is now: %s" key))
             (or (org-entry-get (point) key t)
                 "")))
```
producing output like this:
```
Our key is currently...

filename

The key symbolp check was hit
Our key is now: filename
Second time - Our key is now: ID
Final inner point - Our key is now: ID
"xxAHU-24"
```

So, for some reason it is evaluating the final setq in the `when` condition, without conditionally running it?  Or maybe `key` is being overshadowed by something due to lexical/dynamic scoping... I'm going to try renaming this function variable from key to something else, and perhaps try a wrap in lexical-let and see if that helps, otherwise if it's not scoping related, it might be some oddity with certain Emacs versions (I'm using some later `master` branch build) and the `when` macro itself...

**Comment by ahungry** [comment]
I think I found an MVP failure case:
```
(defun my-test-1 ()
  (setq test-key "Oof"))

(defun my-test (test-key)
  (print "The output is:")
  (my-test-1)
  (print test-key)
  (print "All done..."))

(my-test "Hello")
```
Of course, this prints "Oof" - even with lexical-bindings, I think that guard only performs as expected on the evaluation portion, not on the otherwise cached results of the function, or some other way it is being loaded.

Strangely enough, whether I swap it to `my-key` as a var name, or leave it as `key`, the failure remains - looks like wrapping it in `lexical-let` might solve the issue - but I don't think my MVP failure is 100% related if it's still triggering with the renamed key...

I'll do some more lexical-let testing and probably just push it as such, as I can't see any downside to it, and it might remedy all these open issues...

**Comment by lelit** [comment]
A first quick test tells that this seems fixed indeed! 
Thank you again!
