### ISSUE TITLE
Question: Minimum Supported Emacs Version?

### ISSUE THREAD

**Issue by nickgarber** [ahungry/org-jira#43]
I've noticed that the `org-jira-update-issue` function doesn't update worklog-id's when using the Emacs version on CentOSv7.

It _does_ work on version 25.1.1 on a different machine.

Is there a minimum Emacs version required? 

If this difference is unintended I'd be happy to assist in clearing it up.

**Comment by nickgarber** [comment]
To be more specific, the Emacs version on CentOSv7 is v24.3.1 and it appears that the worklogs are transferring to Jira, but the org-mode LOGBOOK isn't being updated with the worklog-id. 

This causes the entries to appear as if they haven't been sync'd, so they are sent again creating duplicates. This could potentially result in many multiples of duplicates for each worklog if the sync functionality is run unattended.

**Comment by ahungry** [comment]
I think this is related to the org-mode version (and is unintentional).

On a newer Emacs/org-mode, clock entries go into a LOGBOOK drawer - if you manually clock in and out using org-clock, I'm guessing this doesn't happen on your Emacs 24.3.1?

Is there a way to enable the org clock drawer on older Emacs?  If so, I may just recommend that setting be set/forced before using this feature - otherwise, I'll have to update the clock parser to handle when the entries are not in a single collapsible drawer location.

**Comment by nickgarber** [comment]
Not sure about the defaults but in my config the LOGBOOK drawer is used for all clocking logs. 

Just noticed the worklog attributes like `:id:` and the description are being added _after_ the LOGBOOK ends.

So instead of being interleaved they were getting added behind it.

I did some testing with the pre-merge worklog branch version so I'm going do some additional testing to make sure it's a current problem.

**Comment by nickgarber** [comment]
The problem I experienced seemed to be tied to having the LOGBOOK drawer before the PROPERTIES drawer. 

Once I fixed this so that the LOGBOOK is after the PROPERTIES drawer it looks to be working as desired.

As far as I understanding it, this isn't a bug with org-jira, and can be checked for by running a `M-x org-lint` self check.

**Comment by ahungry** [comment]
Sweet, TIL about org-lint :smile:
