### ISSUE TITLE
Real status name instead of statusCategory name

### ISSUE THREAD

**Issue by vxcamiloxv** [ahungry/org-jira#5]
Thanks for resurrect org-jira, I have a question.

Why get status value in ['org-jira-get-issue-val'](https://github.com/ahungry/org-jira/blob/master/org-jira.el#L414) by category name instead of real name of status ?

```
 (org-jira-find-value issue 'fields 'status 'name)
```

instead of
```
 (org-jira-find-value issue 'fields 'status 'statusCategory 'name)
```

**Comment by ahungry** [comment]
I have to look into this still, just letting you know I saw the comment! :)

**Comment by ahungry** [comment]
I think the original reason was so that things like RESOLVED would show up as DONE in the tag, which is good for setting the org TODO/DONE flag, but not good when there are multiple status levels, like 'QA', with an actual statusCategory of 'In-Progress'.

I think instead of simply changing, I am going to add another org attribute (status-category) and will keep the current value in there, and the actual real name in the status attribute, unless it turns out statusCategory is just redundant entirely.

**Comment by ahungry** [comment]
Fixed to use status as suggested, not statusCategory as it isn't needed

**Comment by vxcamiloxv** [comment]
Thanks :+1:
