### ISSUE TITLE
Segregate JIRA issues in OPS.org

### ISSUE THREAD

**Issue by shakthimaan** [ahungry/org-jira#51]
How can I best segregate the JIRA issues in OPS.org file. I want something like:

```
* May 2017
** TODO JIRA-4
** DONE JIRA-3
* April 2017
** TODO JIRA-1
** DONE JIRA-2
```

**Comment by ahungry** [comment]
Due to the somewhat static way in which issues are retrieved, I don't think this will work out for you if you plan to further sync the issues in the future.

If you order them in a custom way, that should be fine, as resyncing/fetching new issues will not change the order of existing issues.

The problem is with the multiple nested headings (the org-jira functions will always want the issue itself at the top level).
