### ISSUE TITLE
Specify org-files to sync projects

### ISSUE THREAD

**Issue by chase-dwelle** [ahungry/org-jira#54]
I would like it to be possible to specify which file projects sync their issues to. I already have existing org-files for each project I have in Jira (I keep them as a sort of lab notebook), and would like to sync to these files instead of the ones in `~/.org-jira/` so I don't have to jump back and forth between files.

Similar to issue #51, I would like to have some order to my issues after I am done working with them. I can get around the requirement being at a top-level subtree, I can just move them after I sync the issues.

**Comment by TinySong** [comment]
I think it's great idea, @ahungry what do you think? shall we implement this feature ?

**Comment by ahungry** [comment]
Sounds good to me!

- Matt 
-------- Original message --------From: song <notifications@github.com> Date: 7/1/17  12:20 AM  (GMT-05:00) To: ahungry/org-jira <org-jira@noreply.github.com> Cc: Matthew Carter <m@ahungry.com>, Mention <mention@noreply.github.com> Subject: Re: [ahungry/org-jira] Specify org-files to sync projects (#54) 
I think it's great idea, @ahungry what do you think? shall we implement this feature ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ahungry/org-jira","title":"ahungry/org-jira","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ahungry/org-jira"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TinySong in #54: I think it's great idea, @ahungry what do you think? shall we implement this feature ?"}],"action":{"name":"View Issue","url":"https://github.com/ahungry/org-jira/issues/54#issuecomment-312409412"}}}
